name: snu_connect
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  anim_search_bar: ^2.0.2
  bottom_sheet_expandable_bar: ^0.1.2
  bouncing_widget: ^2.0.0
  bubble: ^1.2.1
  clipboard: ^0.1.3
  cloud_firestore: ^3.1.0
  date_time_picker_widget: ^1.0.1+4
  delayed_display: ^2.0.0
  filter_list: ^1.0.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  flip_card: ^0.5.0
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.3.0
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  profanity_filter: ^2.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/profilelogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
